import type { FastifyInstance } from "fastify";
import { DateTime } from "luxon";
import type { z } from "zod";
import type { AuthProvider } from "../../shared/auth/auth-provider.js";
import { requireApplicationUser } from "../../shared/application-user/require-application-user.js";
import { AppError } from "../../shared/errors/app-error.js";
import type { DataStore } from "../../database/data-store.js";
import { BookingApplicationService } from "./booking.service.js";
import type { BookingStore } from "./booking.types.js";
import { availabilityQuerySchema, bookingIdParamsSchema, bookingListQuerySchema, createBookingSchema, lookupBookingSchema, statusUpdateSchema } from "./booking.schema.js";
function parse<T>(schema:z.ZodType<T>,input:unknown){const result=schema.safeParse(input);if(!result.success)throw new AppError(400,"VALIDATION_ERROR","The request is invalid.");return result.data;}
export function registerPublicBookingRoutes(app:FastifyInstance,store:BookingStore){const service=new BookingApplicationService(store);app.get("/api/v1/public/booking/availability",async request=>{const input=parse(availabilityQuerySchema,request.query);return service.availability({...(input.serviceId?{serviceId:input.serviceId}:{}),...(input.serviceSlug?{serviceSlug:input.serviceSlug}:{})},input.date);});app.post("/api/v1/public/bookings",{bodyLimit:16_384},async(request,reply)=>{const input=parse(createBookingSchema,request.body);const {serviceId,serviceSlug,notes,...required}=input;return reply.code(201).send(await service.create({...required,...(serviceId?{serviceId}:{}),...(serviceSlug?{serviceSlug}:{}),...(notes?{notes}:{})}));});app.post("/api/v1/public/bookings/lookup",{bodyLimit:4_096},async request=>{const input=parse(lookupBookingSchema,request.body);return service.lookup(input.bookingNumber,input.email);});}
export function registerAdminBookingRoutes(app:FastifyInstance,authProvider:AuthProvider,dataStore:DataStore,store:BookingStore){const service=new BookingApplicationService(store);app.get("/api/v1/bookings",async request=>{const user=await requireApplicationUser(request,authProvider,dataStore);const input=parse(bookingListQuerySchema,request.query);const zone=user.business.timezone;const result=await store.listBookings({businessId:user.businessId,page:input.page,limit:input.limit,sort:input.sort,order:input.order,...(input.search?{search:input.search}:{}),...(input.status?{status:input.status}:{}),...(input.serviceId?{serviceId:input.serviceId}:{}),...(input.dateFrom?{dateFrom:DateTime.fromISO(input.dateFrom,{zone}).startOf("day").toUTC().toJSDate()}:{}),...(input.dateTo?{dateTo:DateTime.fromISO(input.dateTo,{zone}).plus({days:1}).startOf("day").toUTC().toJSDate()}:{} )});return {...result,page:input.page,limit:input.limit};});app.get("/api/v1/bookings/:bookingId",async request=>{const user=await requireApplicationUser(request,authProvider,dataStore);const {bookingId}=parse(bookingIdParamsSchema,request.params);const booking=await store.findBooking(user.businessId,bookingId);if(!booking)throw new AppError(404,"BOOKING_NOT_FOUND","Booking not found.");return booking;});app.patch("/api/v1/bookings/:bookingId/status",async request=>{const user=await requireApplicationUser(request,authProvider,dataStore);const {bookingId}=parse(bookingIdParamsSchema,request.params);const {status}=parse(statusUpdateSchema,request.body);return service.updateStatus(user.businessId,bookingId,status);});}
