import type {FastifyInstance} from "fastify";import type {z} from "zod";import type {AuthProvider} from "../../shared/auth/auth-provider.js";import type {DataStore} from "../../database/data-store.js";import {requireApplicationUser,requireServiceManager} from "../../shared/application-user/require-application-user.js";import {AppError} from "../../shared/errors/app-error.js";import {idParams,paymentBody,saleBody,saleList} from "./sale.schema.js";import {PrismaSaleStore} from "./prisma-sale.store.js";
function parse<T>(schema:z.ZodType<T>,value:unknown){const r=schema.safeParse(value);if(!r.success)throw new AppError(400,"VALIDATION_ERROR","The request is invalid.");return r.data}
function mapped(error:unknown):never{const code=typeof error==="object"&&error&&"code" in error?String(error.code):"";const map:Record<string,[number,string]>={SALE_NOT_FOUND:[404,"Sale not found."],PRODUCT_NOT_FOUND:[404,"Product not found."],SERVICE_NOT_FOUND:[404,"Service not found."],CUSTOMER_NOT_FOUND:[404,"Customer not found."],BOOKING_NOT_FOUND:[404,"Booking not found."],PRODUCT_INACTIVE:[409,"Product is inactive."],SERVICE_INACTIVE:[409,"Service is inactive."],INSUFFICIENT_STOCK:[409,"Insufficient stock."],STOCK_CONFLICT:[409,"Inventory changed concurrently."],INVALID_SALE_STATE:[409,"Invalid sale state."],INVALID_DISCOUNT:[400,"Discount exceeds subtotal."],BOOKING_CUSTOMER_MISMATCH:[409,"Booking customer does not match."],PRICE_OVERRIDE_FORBIDDEN:[403,"Price override is not permitted."],SERVICE_PRICE_REQUIRED:[400,"A service price is required."],PRODUCT_PRICE_REQUIRED:[400,"A product price is required."],PAYMENT_EXCEEDS_REMAINING:[409,"Payment exceeds the remaining amount."],PAID_SALE_CANNOT_BE_CANCELLED:[409,"Paid sales require a manual refund before cancellation."],P2034:[409,"Concurrent transaction conflict."]};const hit=map[code];if(hit)throw new AppError(hit[0],code,hit[1]);throw error}
export function registerSaleRoutes(app:FastifyInstance,auth:AuthProvider,data:DataStore,store:PrismaSaleStore){
 app.get("/api/v1/sales/summary",async req=>{const u=await requireApplicationUser(req,auth,data);return store.summary(u.businessId)});
 app.get("/api/v1/sales",async req=>{const u=await requireApplicationUser(req,auth,data);const q=parse(saleList,req.query);const r=await store.list({businessId:u.businessId,...q});return{...r,page:q.page,limit:q.limit}});
 app.post("/api/v1/sales",async(req,reply)=>{const u=await requireApplicationUser(req,auth,data);const b=parse(saleBody,req.body);try{return reply.code(201).send(await store.create({businessId:u.businessId,actorId:u.id,role:u.role,...b}))}catch(e){mapped(e)}});
 app.get("/api/v1/sales/:saleId",async req=>{const u=await requireApplicationUser(req,auth,data);const {saleId}=parse(idParams,req.params);const s=await store.get(u.businessId,saleId);if(!s)throw new AppError(404,"SALE_NOT_FOUND","Sale not found.");return s});
 app.patch("/api/v1/sales/:saleId",async req=>{const u=await requireApplicationUser(req,auth,data);const {saleId}=parse(idParams,req.params);const b=parse(saleBody,req.body);try{return await store.update(saleId,{businessId:u.businessId,actorId:u.id,role:u.role,...b})}catch(e){mapped(e)}});
 app.post("/api/v1/sales/:saleId/complete",async req=>{const u=await requireApplicationUser(req,auth,data);const {saleId}=parse(idParams,req.params);try{return await store.complete(u.businessId,saleId,u.id)}catch(e){mapped(e)}});
 app.post("/api/v1/sales/:saleId/cancel",async req=>{const u=await requireApplicationUser(req,auth,data);requireServiceManager(u.role);const {saleId}=parse(idParams,req.params);try{return await store.cancel(u.businessId,saleId,u.id)}catch(e){mapped(e)}});
 app.get("/api/v1/sales/:saleId/payments",async req=>{const u=await requireApplicationUser(req,auth,data);const {saleId}=parse(idParams,req.params);try{return await store.payments(u.businessId,saleId)}catch(e){mapped(e)}});
 app.post("/api/v1/sales/:saleId/payments",async(req,reply)=>{const u=await requireApplicationUser(req,auth,data);requireServiceManager(u.role);const {saleId}=parse(idParams,req.params);const b=parse(paymentBody,req.body);try{return reply.code(201).send(await store.addPayment(u.businessId,saleId,u.id,b))}catch(e){mapped(e)}});
}
