// @vitest-environment jsdom
import "@testing-library/jest-dom/vitest";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { AppPreferencesProvider } from "../../context";
import { bookingApi } from "../../features/bookings/api";
import { BookingPage, bookingCustomerSchema, isContactStepValid } from "./booking";

vi.mock("framer-motion",async importOriginal=>({...await importOriginal<typeof import("framer-motion")>(),useReducedMotion:()=>true}));
afterEach(cleanup);
const service={id:"service-1",slug:"service-a",nameDe:"Testleistung",nameEn:"Test service",durationMinutes:60};
function renderBooking(){localStorage.setItem("language","en");const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});return render(<AppPreferencesProvider><QueryClientProvider client={client}><BookingPage initialService="service-a"/></QueryClientProvider></AppPreferencesProvider>)}
async function reachContact(user:ReturnType<typeof userEvent.setup>){await screen.findByRole("option",{name:"Test service"});await user.click(screen.getByRole("button",{name:"Next"}));await waitFor(()=>expect(document.querySelector('input[type="date"]')).not.toBeNull());await user.click(screen.getByRole("button",{name:"Next"}));await screen.findByRole("button",{name:"09:00"});await user.click(screen.getByRole("button",{name:"09:00"}));await user.click(screen.getByRole("button",{name:"Next"}));await screen.findByRole("textbox",{name:"First name"})}
beforeEach(()=>{vi.restoreAllMocks();vi.spyOn(bookingApi,"services").mockResolvedValue([service]);vi.spyOn(bookingApi,"availability").mockResolvedValue({date:"2026-08-20",timezone:"Europe/Berlin",slots:[{time:"09:00",available:true}]})});
describe("booking contact step",()=>{
 it("validates only required contact fields, accepts an empty note and preserves values through Review and Back",async()=>{const create=vi.spyOn(bookingApi,"create").mockResolvedValue({bookingNumber:"BK-TEST",status:"PENDING",startsAt:"2026-08-20T07:00:00.000Z",service:{nameDe:"Testleistung",nameEn:"Test service"}});const user=userEvent.setup();renderBooking();await reachContact(user);const next=screen.getByRole("button",{name:"Next"});expect(next).toBeDisabled();await user.type(screen.getByRole("textbox",{name:"First name"}),"Ada");await user.type(screen.getByRole("textbox",{name:"Last name"}),"Lovelace");await user.type(screen.getByRole("textbox",{name:"Email"}),"invalid");await user.type(screen.getByRole("textbox",{name:"Phone"}),"017612345678");expect(await screen.findByText("Please enter a valid email address.")).toBeVisible();expect(next).toBeDisabled();fireEvent.change(screen.getByDisplayValue("invalid"),{target:{value:"ada@example.invalid"}});await waitFor(()=>expect(next).toBeEnabled());expect(screen.getByRole("textbox",{name:"Notes (optional)"})).toHaveValue("");await user.click(next);expect(await screen.findByRole("heading",{name:"Review booking"})).toBeVisible();expect(screen.getByText(/Ada Lovelace/)).toHaveTextContent("ada@example.invalid");expect(screen.getByText(/09:00/)).toBeVisible();expect(create).not.toHaveBeenCalled();await user.click(screen.getByRole("button",{name:"Back"}));expect(await screen.findByRole("textbox",{name:"First name"})).toHaveValue("Ada");expect(screen.getByRole("textbox",{name:"Phone"})).toHaveValue("017612345678");await user.click(screen.getByRole("button",{name:"Next"}));await screen.findByRole("heading",{name:"Review booking"});expect(create).not.toHaveBeenCalled();await user.click(screen.getByRole("button",{name:"Request appointment"}));expect(await screen.findByRole("heading",{name:"Your booking was saved."})).toBeVisible();expect(create).toHaveBeenCalledTimes(1)});
 it("keeps the booking data on a final API error",async()=>{vi.spyOn(bookingApi,"create").mockRejectedValue(new Error("BOOKING_SLOT_UNAVAILABLE"));const user=userEvent.setup();renderBooking();await reachContact(user);await user.type(screen.getByRole("textbox",{name:"First name"}),"Grace");await user.type(screen.getByRole("textbox",{name:"Last name"}),"Hopper");await user.type(screen.getByRole("textbox",{name:"Email"}),"grace@example.invalid");await user.type(screen.getByRole("textbox",{name:"Phone"}),"017698765432");await user.click(screen.getByRole("button",{name:"Next"}));await user.click(await screen.findByRole("button",{name:"Request appointment"}));expect(await screen.findByText("This slot is no longer available.")).toBeVisible();await user.click(screen.getByRole("button",{name:"Back"}));expect(await screen.findByRole("textbox",{name:"First name"})).toHaveValue("Grace");expect(screen.getByRole("textbox",{name:"Email"})).toHaveValue("grace@example.invalid")});
});
describe("contact schema",()=>{it("rejects empty required fields",()=>expect(isContactStepValid({firstName:"",lastName:"",email:"",phone:""})).toBe(false));it("accepts a normal German mobile number and an empty optional note",()=>expect(isContactStepValid({firstName:"Ada",lastName:"Lovelace",email:"ada@example.invalid",phone:"017612345678",notes:""})).toBe(true));it("rejects an invalid email",()=>expect(bookingCustomerSchema.safeParse({firstName:"Ada",lastName:"Lovelace",email:"invalid",phone:"017612345678"}).success).toBe(false))});
