import {afterAll,beforeAll,describe,expect,it} from "vitest";import {buildApp} from "../src/app.js";import type {ServerEnvironment} from "../src/config/env.js";import {PrismaDataStore} from "../src/database/prisma.js";import type {AuthProvider} from "../src/shared/auth/auth-provider.js";
const url=process.env.TEST_DATABASE_URL;if(!url)throw new Error("TEST_DATABASE_URL is required; inventory integration tests must not be skipped.");
const store=new PrismaDataStore(url);const suffix=Date.now().toString(36);let app:Awaited<ReturnType<typeof buildApp>>;let businessId="";let otherBusinessId="";let adminId="";const adminClerk="inventory-admin-"+suffix;const employeeClerk="inventory-employee-"+suffix;const otherClerk="inventory-other-"+suffix;
const environment:ServerEnvironment={NODE_ENV:"test",HOST:"127.0.0.1",PORT:3998,LOG_LEVEL:"silent",FRONTEND_ORIGIN:"http://localhost:5173",CLERK_PUBLISHABLE_KEY:"pk_test_placeholder",CLERK_SECRET_KEY:"sk_test_placeholder",DATABASE_URL:url};const auth:AuthProvider={getIdentity(request){const userId=request.headers["x-test-user-id"];return typeof userId==="string"?{userId,sessionId:"test",organizationId:null}:null}};const headers=(userId=adminClerk)=>({"x-test-user-id":userId});
beforeAll(async()=>{const b=await store.client.business.create({data:{name:"Inventory Test",slug:"inventory-"+suffix}});businessId=b.id;const other=await store.client.business.create({data:{name:"Other Inventory",slug:"other-inventory-"+suffix}});otherBusinessId=other.id;const admin=await store.client.user.create({data:{businessId,clerkUserId:adminClerk,role:"ADMIN"}});adminId=admin.id;await store.client.user.create({data:{businessId,clerkUserId:employeeClerk,role:"EMPLOYEE"}});await store.client.user.create({data:{businessId:otherBusinessId,clerkUserId:otherClerk,role:"ADMIN"}});app=await buildApp({environment,authProvider:auth,dataStore:store,logger:false})});
afterAll(async()=>{if(app)await app.close();await store.client.inventoryMovement.deleteMany({where:{businessId:{in:[businessId,otherBusinessId]}}});await store.client.product.deleteMany({where:{businessId:{in:[businessId,otherBusinessId]}}});await store.client.user.deleteMany({where:{businessId:{in:[businessId,otherBusinessId]}}});await store.client.business.deleteMany({where:{id:{in:[businessId,otherBusinessId]}}});await store.disconnect()});
describe("PostgreSQL products and inventory",()=>{
 let productId="";
 it("creates a product and matching initial movement",async()=>{const response=await app.inject({method:"POST",url:"/api/v1/products",headers:headers(),payload:{sku:" test sku ",name:"Test Product",description:"Test",category:"CLEANING_CHEMICAL",imageUrl:"https://example.test/product.jpg",specifications:{volumeMl:1000,unit:"L",intendedUse:{de:"Innenraum",en:"Interior"}},salePriceMinor:1299,costPriceMinor:700,initialStock:5,minimumStock:5,isActive:true}});expect(response.statusCode).toBe(201);const body=response.json<{id:string;sku:string;stockQuantity:number;lowStock:boolean}>();productId=body.id;expect(body).toMatchObject({sku:"TEST-SKU",stockQuantity:5,lowStock:true});const movement=await store.client.inventoryMovement.findFirstOrThrow({where:{productId}});expect(movement).toMatchObject({type:"INITIAL",quantityBefore:0,quantityDelta:5,quantityAfter:5,createdByUserId:adminId})});
 it("validates controlled product specifications and category filters",async()=>{const invalid=await app.inject({method:"POST",url:"/api/v1/products",headers:headers(),payload:{sku:"INVALID-SPEC",name:"Invalid",category:"WINDOW_FILM",salePriceMinor:0,specifications:{vltPercent:120,unknownField:"rejected"}}});expect(invalid.statusCode).toBe(400);const filtered=await app.inject({method:"GET",url:"/api/v1/products?category=CLEANING_CHEMICAL",headers:headers()});expect(filtered.statusCode).toBe(200);const filteredBody=filtered.json<{items:Array<{id:string}>}>();expect(filteredBody.items.some(item=>item.id===productId)).toBe(true);expect((await app.inject({method:"GET",url:"/api/v1/products?category=UNKNOWN",headers:headers()})).statusCode).toBe(400)});
 it("rejects duplicate SKU in one business but allows it in another",async()=>{const payload={sku:"TEST-SKU",name:"Duplicate",salePriceMinor:100,initialStock:0,minimumStock:0,isActive:true};expect((await app.inject({method:"POST",url:"/api/v1/products",headers:headers(),payload})).statusCode).toBe(409);expect((await app.inject({method:"POST",url:"/api/v1/products",headers:headers(otherClerk),payload})).statusCode).toBe(201)});
 it("updates metadata, rejects direct stock mutation and enforces employee read-only",async()=>{expect((await app.inject({method:"PATCH",url:"/api/v1/products/"+productId,headers:headers(),payload:{stockQuantity:99}})).statusCode).toBe(400);const updated=await app.inject({method:"PATCH",url:"/api/v1/products/"+productId,headers:headers(),payload:{name:"Updated Product",minimumStock:3}});expect(updated.statusCode).toBe(200);expect(updated.json()).toMatchObject({name:"Updated Product",stockQuantity:5,minimumStock:3,lowStock:false});expect((await app.inject({method:"GET",url:"/api/v1/products/"+productId,headers:headers(employeeClerk)})).statusCode).toBe(200);expect((await app.inject({method:"POST",url:"/api/v1/products",headers:headers(employeeClerk),payload:{sku:"DENIED",name:"Denied",salePriceMinor:1,initialStock:0,minimumStock:0}})).statusCode).toBe(403)});
 it("records positive and negative adjustments consistently and orders history",async()=>{expect((await app.inject({method:"POST",url:"/api/v1/products/"+productId+"/inventory/adjust",headers:headers(),payload:{quantityDelta:5,reason:"Purchase"}})).json()).toMatchObject({stockQuantity:10});expect((await app.inject({method:"POST",url:"/api/v1/products/"+productId+"/inventory/adjust",headers:headers(),payload:{quantityDelta:-3,reason:"Damage"}})).json()).toMatchObject({stockQuantity:7});const history=await app.inject({method:"GET",url:"/api/v1/products/"+productId+"/inventory",headers:headers()});expect(history.statusCode).toBe(200);const items=history.json<{items:Array<{quantityBefore:number;quantityDelta:number;quantityAfter:number;createdByUser:{id:string}|null}>}>().items;expect(items.length).toBe(3);for(const item of items)expect(item.quantityAfter).toBe(item.quantityBefore+item.quantityDelta);expect(items[0]?.createdByUser?.id).toBe(adminId)});
 it("rejects zero, insufficient and inactive-product adjustments",async()=>{expect((await app.inject({method:"POST",url:"/api/v1/products/"+productId+"/inventory/adjust",headers:headers(),payload:{quantityDelta:0,reason:"Zero"}})).statusCode).toBe(400);expect((await app.inject({method:"POST",url:"/api/v1/products/"+productId+"/inventory/adjust",headers:headers(),payload:{quantityDelta:-100,reason:"Too much"}})).statusCode).toBe(409);expect((await app.inject({method:"DELETE",url:"/api/v1/products/"+productId,headers:headers()})).statusCode).toBe(200);expect((await app.inject({method:"POST",url:"/api/v1/products/"+productId+"/inventory/adjust",headers:headers(),payload:{quantityDelta:1,reason:"Inactive"}})).statusCode).toBe(409);expect(await store.client.product.findUnique({where:{id:productId}})).not.toBeNull()});
 it("computes low stock for equal, below and above thresholds",async()=>{const cases=[["LOW-EQUAL",5,5,true],["LOW-BELOW",2,5,true],["LOW-ABOVE",6,5,false]] as const;for(const [sku,initialStock,minimumStock,lowStock] of cases){const response=await app.inject({method:"POST",url:"/api/v1/products",headers:headers(),payload:{sku,name:sku,salePriceMinor:1,initialStock,minimumStock}});expect(response.json<{lowStock:boolean}>().lowStock).toBe(lowStock)}const low=await app.inject({method:"GET",url:"/api/v1/products?lowStock=true&limit=100",headers:headers()});expect(low.statusCode).toBe(200);expect(low.json<{items:Array<{sku:string}>}>().items.map(p=>p.sku)).toEqual(expect.arrayContaining(["LOW-EQUAL","LOW-BELOW"]))});
 it("prevents lost updates and negative stock under concurrent decrements",async()=>{const made=await app.inject({method:"POST",url:"/api/v1/products",headers:headers(),payload:{sku:"CONCURRENT",name:"Concurrent",salePriceMinor:1,initialStock:5,minimumStock:0}});const id=made.json<{id:string}>().id;const responses=await Promise.all([1,2].map(()=>app.inject({method:"POST",url:"/api/v1/products/"+id+"/inventory/adjust",headers:headers(),payload:{quantityDelta:-4,reason:"Concurrent"}})));expect(responses.map(r=>r.statusCode).sort()).toEqual([200,409]);expect((await store.client.product.findUniqueOrThrow({where:{id}})).stockQuantity).toBe(1);expect(await store.client.inventoryMovement.count({where:{productId:id}})).toBe(2)});
 it("enforces business isolation and database constraints",async()=>{expect((await app.inject({method:"GET",url:"/api/v1/products/"+productId,headers:headers(otherClerk)})).statusCode).toBe(404);await expect(store.client.product.create({data:{businessId,sku:"NEGATIVE",name:"Negative",salePriceMinor:1,stockQuantity:-1,minimumStock:0}})).rejects.toThrow()});
});
