/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSalesRouteImport } from './routes/admin/sales'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminEmployeesRouteImport } from './routes/admin/employees'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as PublicMyBookingRouteImport } from './routes/_public/my-booking'
import { Route as PublicImpressumRouteImport } from './routes/_public/impressum'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicBookingRouteImport } from './routes/_public/booking'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicServicesIndexRouteImport } from './routes/_public/services.index'
import { Route as PublicServicesSlugRouteImport } from './routes/_public/services.$slug'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const PublicMyBookingRoute = PublicMyBookingRouteImport.update({
  id: '/my-booking',
  path: '/my-booking',
  getParentRoute: () => PublicRoute,
} as any)
const PublicImpressumRoute = PublicImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBookingRoute = PublicBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicServicesIndexRoute = PublicServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicServicesSlugRoute = PublicServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/about': typeof PublicAboutRoute
  '/booking': typeof PublicBookingRoute
  '/contact': typeof PublicContactRoute
  '/impressum': typeof PublicImpressumRoute
  '/my-booking': typeof PublicMyBookingRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/services/$slug': typeof PublicServicesSlugRoute
  '/services/': typeof PublicServicesIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/about': typeof PublicAboutRoute
  '/booking': typeof PublicBookingRoute
  '/contact': typeof PublicContactRoute
  '/impressum': typeof PublicImpressumRoute
  '/my-booking': typeof PublicMyBookingRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/services/$slug': typeof PublicServicesSlugRoute
  '/services': typeof PublicServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/booking': typeof PublicBookingRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/impressum': typeof PublicImpressumRoute
  '/_public/my-booking': typeof PublicMyBookingRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/services/$slug': typeof PublicServicesSlugRoute
  '/_public/services/': typeof PublicServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/sign-in'
    | '/about'
    | '/booking'
    | '/contact'
    | '/impressum'
    | '/my-booking'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/employees'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/'
    | '/services/$slug'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/about'
    | '/booking'
    | '/contact'
    | '/impressum'
    | '/my-booking'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/employees'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/settings'
    | '/'
    | '/admin'
    | '/services/$slug'
    | '/services'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/sign-in'
    | '/_public/about'
    | '/_public/booking'
    | '/_public/contact'
    | '/_public/impressum'
    | '/_public/my-booking'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/employees'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/settings'
    | '/_public/'
    | '/admin/'
    | '/_public/services/$slug'
    | '/_public/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/my-booking': {
      id: '/_public/my-booking'
      path: '/my-booking'
      fullPath: '/my-booking'
      preLoaderRoute: typeof PublicMyBookingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/impressum': {
      id: '/_public/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof PublicImpressumRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/booking': {
      id: '/_public/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof PublicBookingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/services/': {
      id: '/_public/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof PublicServicesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/services/$slug': {
      id: '/_public/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof PublicServicesSlugRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicBookingRoute: typeof PublicBookingRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicImpressumRoute: typeof PublicImpressumRoute
  PublicMyBookingRoute: typeof PublicMyBookingRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicServicesSlugRoute: typeof PublicServicesSlugRoute
  PublicServicesIndexRoute: typeof PublicServicesIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicBookingRoute: PublicBookingRoute,
  PublicContactRoute: PublicContactRoute,
  PublicImpressumRoute: PublicImpressumRoute,
  PublicMyBookingRoute: PublicMyBookingRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicServicesSlugRoute: PublicServicesSlugRoute,
  PublicServicesIndexRoute: PublicServicesIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
