import type {PrismaClient} from "../../generated/prisma/client.js";
import type {CreateProductInput,ProductListInput,ProductStore,UpdateProductInput} from "./product.types.js";
export function normalizeSku(value:string){return value.trim().toUpperCase().replace(/\s+/g,"-")}
export class PrismaProductStore implements ProductStore{
 constructor(private readonly prisma:PrismaClient){}
 async list(input:ProductListInput){const where={businessId:input.businessId,...(input.search?{OR:[{name:{contains:input.search,mode:"insensitive" as const}},{sku:{contains:input.search,mode:"insensitive" as const}},{category:{contains:input.search,mode:"insensitive" as const}}]}:{}),...(input.category?{category:{equals:input.category,mode:"insensitive" as const}}:{}),...(input.isActive!==undefined?{isActive:input.isActive}:{}),...(input.lowStock!==undefined?(input.lowStock?{stockQuantity:{lte:this.prisma.product.fields.minimumStock}}:{stockQuantity:{gt:this.prisma.product.fields.minimumStock}}):{})};const [items,total]=await Promise.all([this.prisma.product.findMany({where,orderBy:{[input.sort]:input.order},skip:(input.page-1)*input.limit,take:input.limit}),this.prisma.product.count({where})]);return{items,total}}
 find(businessId:string,id:string){return this.prisma.product.findFirst({where:{id,businessId}})}
 create(input:CreateProductInput){return this.prisma.$transaction(async tx=>{const product=await tx.product.create({data:{businessId:input.businessId,sku:normalizeSku(input.sku),name:input.name,description:input.description??null,category:input.category,imageUrl:input.imageUrl??null,...(input.specifications!==undefined?{specifications:input.specifications}:{}),salePriceMinor:input.salePriceMinor,costPriceMinor:input.costPriceMinor??null,stockQuantity:input.initialStock,minimumStock:input.minimumStock,isActive:input.isActive}});if(input.initialStock>0)await tx.inventoryMovement.create({data:{businessId:input.businessId,productId:product.id,type:"INITIAL",quantityDelta:input.initialStock,quantityBefore:0,quantityAfter:input.initialStock,reason:"Initial stock",createdByUserId:input.createdByUserId}});return product},{isolationLevel:"Serializable"})}
 async update(businessId:string,id:string,input:UpdateProductInput){const data={...(input.sku!==undefined?{sku:normalizeSku(input.sku)}:{}),...(input.name!==undefined?{name:input.name}:{}),...(input.description!==undefined?{description:input.description}:{}),...(input.category!==undefined?{category:input.category}:{}),...(input.imageUrl!==undefined?{imageUrl:input.imageUrl}:{}),...(input.specifications!==undefined?{specifications:input.specifications}:{}),...(input.salePriceMinor!==undefined?{salePriceMinor:input.salePriceMinor}:{}),...(input.costPriceMinor!==undefined?{costPriceMinor:input.costPriceMinor}:{}),...(input.minimumStock!==undefined?{minimumStock:input.minimumStock}:{}),...(input.isActive!==undefined?{isActive:input.isActive}:{})};const result=await this.prisma.product.updateMany({where:{id,businessId},data});return result.count?this.find(businessId,id):null}
 async deactivate(businessId:string,id:string){const result=await this.prisma.product.updateMany({where:{id,businessId},data:{isActive:false}});return result.count?this.find(businessId,id):null}
 async adjust(businessId:string,id:string,delta:number,reason:string|null,actorId:string){return this.prisma.$transaction(async tx=>{await tx.$executeRawUnsafe("SELECT pg_advisory_xact_lock(hashtextextended($1, 0))",businessId+":"+id);const product=await tx.product.findFirst({where:{id,businessId}});if(!product)throw Object.assign(new Error("Product not found"),{code:"PRODUCT_NOT_FOUND"});if(!product.isActive)throw Object.assign(new Error("Product inactive"),{code:"PRODUCT_INACTIVE"});const after=product.stockQuantity+delta;if(after<0)throw Object.assign(new Error("Insufficient stock"),{code:"INSUFFICIENT_STOCK"});const result=await tx.product.updateMany({where:{id,businessId,stockQuantity:product.stockQuantity},data:{stockQuantity:after}});if(result.count!==1)throw Object.assign(new Error("Stock conflict"),{code:"STOCK_CONFLICT"});await tx.inventoryMovement.create({data:{businessId,productId:id,type:"ADJUSTMENT",quantityDelta:delta,quantityBefore:product.stockQuantity,quantityAfter:after,reason,createdByUserId:actorId}});return tx.product.findUniqueOrThrow({where:{id}})},{isolationLevel:"Serializable"})}
 async history(businessId:string,id:string,page:number,limit:number){const where={businessId,productId:id};const [items,total]=await Promise.all([this.prisma.inventoryMovement.findMany({where,select:{id:true,type:true,quantityDelta:true,quantityBefore:true,quantityAfter:true,reason:true,referenceType:true,referenceId:true,createdAt:true,createdByUser:{select:{id:true,role:true}}},orderBy:{createdAt:"desc"},skip:(page-1)*limit,take:limit}),this.prisma.inventoryMovement.count({where})]);return{items,total}}
}
