import type {FastifyInstance} from "fastify";import type {z} from "zod";
import type {AuthProvider} from "../../shared/auth/auth-provider.js";import type {DataStore} from "../../database/data-store.js";import {requireApplicationUser,requireServiceManager} from "../../shared/application-user/require-application-user.js";import {AppError} from "../../shared/errors/app-error.js";
import type {ProductStore} from "./product.types.js";import {adjustInventorySchema,createProductSchema,historyQuery,listProductsQuery,productIdParams,updateProductSchema} from "./product.schema.js";
function parse<T>(schema:z.ZodType<T>,value:unknown){const result=schema.safeParse(value);if(!result.success)throw new AppError(400,"VALIDATION_ERROR","The request is invalid.");return result.data}
function dto<T extends {stockQuantity:number;minimumStock:number}>(product:T){return{...product,lowStock:product.stockQuantity<=product.minimumStock}}
function mapped(error:unknown):never{const code=typeof error==="object"&&error&&"code" in error?String(error.code):"";if(code==="P2002")throw new AppError(409,"SKU_ALREADY_EXISTS","A product with this SKU already exists.");if(code==="PRODUCT_NOT_FOUND")throw new AppError(404,"PRODUCT_NOT_FOUND","Product not found.");if(code==="PRODUCT_INACTIVE")throw new AppError(409,"PRODUCT_INACTIVE","Inactive products cannot be adjusted.");if(code==="INSUFFICIENT_STOCK")throw new AppError(409,"INSUFFICIENT_STOCK","The adjustment would make stock negative.");if(code==="STOCK_CONFLICT"||code==="P2034")throw new AppError(409,"INVENTORY_CONFLICT","The inventory changed concurrently. Retry the request.");throw error}
export function registerProductRoutes(app:FastifyInstance,auth:AuthProvider,dataStore:DataStore,store:ProductStore){
 app.get("/api/v1/products",async request=>{const user=await requireApplicationUser(request,auth,dataStore);const input=parse(listProductsQuery,request.query);const result=await store.list({businessId:user.businessId,page:input.page,limit:input.limit,sort:input.sort,order:input.order,...(input.search?{search:input.search}:{}),...(input.category?{category:input.category}:{}),...(input.isActive!==undefined?{isActive:input.isActive}:{}),...(input.lowStock!==undefined?{lowStock:input.lowStock}:{})});return{...result,items:result.items.map(dto),page:input.page,limit:input.limit}});
 app.post("/api/v1/products",async(request,reply)=>{const user=await requireApplicationUser(request,auth,dataStore);requireServiceManager(user.role);const input=parse(createProductSchema,request.body);try{return reply.code(201).send(dto(await store.create({...input,businessId:user.businessId,createdByUserId:user.id})))}catch(error){mapped(error)}});
 app.get("/api/v1/products/:productId",async request=>{const user=await requireApplicationUser(request,auth,dataStore);const {productId}=parse(productIdParams,request.params);const product=await store.find(user.businessId,productId);if(!product)throw new AppError(404,"PRODUCT_NOT_FOUND","Product not found.");return dto(product)});
 app.patch("/api/v1/products/:productId",async request=>{const user=await requireApplicationUser(request,auth,dataStore);requireServiceManager(user.role);const {productId}=parse(productIdParams,request.params);const input=parse(updateProductSchema,request.body);try{const product=await store.update(user.businessId,productId,input);if(!product)throw new AppError(404,"PRODUCT_NOT_FOUND","Product not found.");return dto(product)}catch(error){mapped(error)}});
 app.delete("/api/v1/products/:productId",async request=>{const user=await requireApplicationUser(request,auth,dataStore);requireServiceManager(user.role);const {productId}=parse(productIdParams,request.params);const product=await store.deactivate(user.businessId,productId);if(!product)throw new AppError(404,"PRODUCT_NOT_FOUND","Product not found.");return dto(product)});
 app.post("/api/v1/products/:productId/inventory/adjust",async request=>{const user=await requireApplicationUser(request,auth,dataStore);requireServiceManager(user.role);const {productId}=parse(productIdParams,request.params);const input=parse(adjustInventorySchema,request.body);try{return dto(await store.adjust(user.businessId,productId,input.quantityDelta,input.reason,user.id))}catch(error){mapped(error)}});
 app.get("/api/v1/products/:productId/inventory",async request=>{const user=await requireApplicationUser(request,auth,dataStore);const {productId}=parse(productIdParams,request.params);const input=parse(historyQuery,request.query);if(!await store.find(user.businessId,productId))throw new AppError(404,"PRODUCT_NOT_FOUND","Product not found.");return{...await store.history(user.businessId,productId,input.page,input.limit),page:input.page,limit:input.limit}});
}
